{% set version = "2.3.0" %}
{% set sha256 = "e4c02874be09790379c0385ec9cc594fc07c1ae9822e4be1c9947df74b304c33" %}

package:
  name: constructor
  version: {{ version }}

source:
  fn: constructor-{{ version }}-osgeo.tar.gz
  url: https://github.com/osgeo-forge/constructor/archive/810f04b08c5b5c17f0668aa3d924286fd8b5575d.tar.gz
  sha256: {{ sha256 }}

build:
  number: 1010
  script: python setup.py install --single-version-externally-managed --record=record.txt
  entry_points:
    - constructor = constructor.main:main

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - conda >=4.5
    - ruamel_yaml
    - pillow >=3.1     # [win]
    - nsis >=3.01      # [win]

test:
  imports:
    - constructor
  commands:
    - constructor --test

about:
  home: http://github.com/conda/constructor
  license: BSD 3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: create installer from conda packages

extra:
  recipe-maintainers:
    - jakirkham
    - mbargull
    - dakcarto
